[package]
name = "prisma"
version = "0.1.0"
authors = ["Tyler Reisinger <reisinger.tyler@gmail.com>"]

[dependencies]
num = "0.1"
approx = "0.1"
angular-units = "0.2.1"

[dev.dependencies]
bencher = "0.1.2"
