[package]
name = "prisma"
version = "0.1.0"
authors = ["Tyler Reisinger <reisinger.tyler@gmail.com>"]

[dependencies]
num-traits = "^0.2"
approx = { version = "^0.3", optional = true }
angular-units = "^0.2.4"

[features]
default = ["approx"]

[dev.dependencies]
bencher = "0.1.2"
approx = "0.3.0"
